version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/App       # Syncs local project files into the container
      - /App/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
